/**
 * Aggregation script.
 *
 * Reads normalised vulnerability records from `src/data/raw/all.json` and
 * produces time-series aggregates for the dashboard charts:
 *
 *   - discovered-by-month.json   — vulnerabilities discovered per month
 *   - fixed-by-month.json        — vulnerabilities patched per month
 *   - patch-lag-by-month.json    — median + p90 patch lag per month
 *   - backlog-by-month.json      — open vulnerabilities per month
 *   - manufacturers.json         — canonical manufacturer list with colours
 *
 * Yearly variants are also generated by rolling up monthly data.
 *
 * Usage: run via `npm run data:build` (after the pipeline), or standalone:
 *   `tsx scripts/aggregate.ts`
 */

import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import type {
  BacklogPoint,
  ManufacturerInfo,
  PatchLagPoint,
  TimeSeriesPoint,
  VulnerabilityRecord,
} from './pipeline/types.js';
import { MANUFACTURERS } from '../src/lib/manufacturers.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = resolve(__dirname, '..', 'src', 'data');
const RAW_DIR = join(DATA_DIR, 'raw');
const AGG_DIR = join(DATA_DIR, 'aggregated');

async function readJson<T>(path: string): Promise<T> {
  const content = await readFile(path, 'utf-8');
  return JSON.parse(content) as T;
}

async function writeJson(path: string, data: unknown): Promise<void> {
  const json = JSON.stringify(data, null, 2) + '\n';
  await writeFile(path, json, 'utf-8');
}

/** Format a date as "YYYY-MM". */
function toMonth(dateStr: string): string {
  return dateStr.slice(0, 7);
}

/** Format a date as "YYYY". */
function toYear(dateStr: string): string {
  return dateStr.slice(0, 4);
}

/** Compute the median of a sorted numeric array. */
function median(sorted: number[]): number {
  if (sorted.length === 0) return 0;
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 0
    ? (sorted[mid - 1] + sorted[mid]) / 2
    : sorted[mid];
}

/** Compute the 90th percentile of a sorted numeric array. */
function p90(sorted: number[]): number {
  if (sorted.length === 0) return 0;
  const idx = Math.ceil(sorted.length * 0.9) - 1;
  return sorted[Math.max(0, Math.min(idx, sorted.length - 1))];
}

/**
 * Aggregate records into time-series points for discovered/fixed charts.
 * @param records  Normalised vulnerability records
 * @param granularity  "month" or "year"
 * @param dateField  Which date field to bucket by
 */
function aggregateTimeSeries(
  records: VulnerabilityRecord[],
  granularity: 'month' | 'year',
  dateField: 'discoveredDate' | 'patchedDate',
): TimeSeriesPoint[] {
  const buckets = new Map<string, number>();

  for (const record of records) {
    const date = record[dateField];
    if (!date) continue;
    const bucket = granularity === 'month' ? toMonth(date) : toYear(date);
    const key = `${bucket}|${record.manufacturer}`;
    buckets.set(key, (buckets.get(key) ?? 0) + 1);
  }

  const points: TimeSeriesPoint[] = [];
  for (const [key, count] of buckets) {
    const [date, manufacturer] = key.split('|');
    points.push({ date, manufacturer, count });
  }

  // Sort by date then manufacturer
  points.sort((a, b) =>
    a.date === b.date
      ? a.manufacturer.localeCompare(b.manufacturer)
      : a.date.localeCompare(b.date),
  );

  return points;
}

/**
 * Aggregate patch-lag data (median + p90 per month/year per manufacturer).
 *
 * Computes two counts per bucket:
 * - `knownCount`: records with a known (non-zero) patch lag — used for the
 *   median/p90 calculation. These are records where the merge logic was
 *   able to find both a discovery and a patch date.
 * - `totalCount`: all records with a patch date in this bucket (the
 *   denominator for data confidence). The difference between `totalCount`
 *   and `knownCount` represents records that had a patch date but no
 *   known discovery date.
 */
function aggregatePatchLag(
  records: VulnerabilityRecord[],
  granularity: 'month' | 'year',
): PatchLagPoint[] {
  // Tracks known patch lags (for median/p90) and total records with
  // a patch date in this bucket (for data confidence)
  const knownBuckets = new Map<string, number[]>();
  const totalCounts = new Map<string, number>();

  for (const record of records) {
    // Count all records with a patch date (for totalCount)
    if (record.patchedDate) {
      const totalBucket = granularity === 'month'
        ? toMonth(record.patchedDate)
        : toYear(record.patchedDate);
      const totalKey = `${totalBucket}|${record.manufacturer}`;
      totalCounts.set(totalKey, (totalCounts.get(totalKey) ?? 0) + 1);
    }

    // Only include records with a known (non-zero) patch lag in the lag calc
    if (record.patchLagDays == null || record.patchLagDays < 0) continue;
    const date = record.patchedDate ?? record.discoveredDate;
    if (!date) continue;
    const bucket = granularity === 'month' ? toMonth(date) : toYear(date);
    const key = `${bucket}|${record.manufacturer}`;
    const arr = knownBuckets.get(key) ?? [];
    arr.push(record.patchLagDays);
    knownBuckets.set(key, arr);
  }

  // Merge the known and total counts into the output points
  const allKeys = new Set([...knownBuckets.keys(), ...totalCounts.keys()]);
  const points: PatchLagPoint[] = [];
  for (const key of allKeys) {
    const [date, manufacturer] = key.split('|');
    const lags = knownBuckets.get(key) ?? [];
    const totalCount = totalCounts.get(key) ?? 0;
    const knownCount = lags.length;

    if (lags.length === 0) {
      // No known patch lags in this bucket — skip the median/p90 but
      // still report the total count so the UI can show "0 of N have
      // known patch lag".
      points.push({
        date,
        manufacturer,
        medianLagDays: 0,
        p90LagDays: 0,
        knownCount: 0,
        totalCount,
      });
      continue;
    }

    const sorted = lags.sort((a, b) => a - b);
    points.push({
      date,
      manufacturer,
      medianLagDays: Math.round(median(sorted)),
      p90LagDays: Math.round(p90(sorted)),
      knownCount,
      totalCount,
    });
  }

  points.sort((a, b) =>
    a.date === b.date
      ? a.manufacturer.localeCompare(b.manufacturer)
      : a.date.localeCompare(b.date),
  );

  return points;
}

/**
 * Aggregate backlog data — for each month/year, count vulnerabilities that
 * were discovered but not yet patched at that point in time.
 */
function aggregateBacklog(
  records: VulnerabilityRecord[],
  granularity: 'month' | 'year',
): BacklogPoint[] {
  // Build a timeline of events: +1 when discovered, -1 when patched
  type Event = { date: string; manufacturer: string; delta: number };
  const events: Event[] = [];

  for (const record of records) {
    if (!record.discoveredDate) continue;
    const discBucket =
      granularity === 'month'
        ? toMonth(record.discoveredDate)
        : toYear(record.discoveredDate);
    events.push({
      date: discBucket,
      manufacturer: record.manufacturer,
      delta: 1,
    });

    if (record.patchedDate) {
      const patchBucket =
        granularity === 'month'
          ? toMonth(record.patchedDate)
          : toYear(record.patchedDate);
      events.push({
        date: patchBucket,
        manufacturer: record.manufacturer,
        delta: -1,
      });
    }
  }

  // Sort events by date
  events.sort((a, b) => a.date.localeCompare(b.date));

  // Walk through events, maintaining a running count per manufacturer
  const runningCount = new Map<string, number>();
  const points: BacklogPoint[] = [];
  let currentDate = '';

  for (const event of events) {
    // Emit a point for the previous date before moving to a new one
    if (event.date !== currentDate && currentDate) {
      for (const [manufacturer, openCount] of runningCount) {
        if (openCount > 0) {
          points.push({ date: currentDate, manufacturer, openCount });
        }
      }
      currentDate = event.date;
    }
    if (!currentDate) currentDate = event.date;

    const key = event.manufacturer;
    runningCount.set(key, (runningCount.get(key) ?? 0) + event.delta);
  }

  // Emit final point
  if (currentDate) {
    for (const [manufacturer, openCount] of runningCount) {
      if (openCount > 0) {
        points.push({ date: currentDate, manufacturer, openCount });
      }
    }
  }

  points.sort((a, b) =>
    a.date === b.date
      ? a.manufacturer.localeCompare(b.manufacturer)
      : a.date.localeCompare(b.date),
  );

  return points;
}

async function main(): Promise<void> {
  console.log('=== VulnTrends aggregation ===\n');

  // Read merged records
  const records = await readJson<VulnerabilityRecord[]>(
    join(RAW_DIR, 'all.json'),
  );
  console.log(`Loaded ${records.length} records from raw/all.json`);

  // Ensure output directory exists
  await mkdir(AGG_DIR, { recursive: true });

  // Generate monthly aggregates
  console.log('Aggregating monthly data...');
  const discoveredMonth = aggregateTimeSeries(records, 'month', 'discoveredDate');
  const fixedMonth = aggregateTimeSeries(records, 'month', 'patchedDate');
  const patchLagMonth = aggregatePatchLag(records, 'month');
  const backlogMonth = aggregateBacklog(records, 'month');

  await writeJson(join(AGG_DIR, 'discovered-by-month.json'), discoveredMonth);
  await writeJson(join(AGG_DIR, 'fixed-by-month.json'), fixedMonth);
  await writeJson(join(AGG_DIR, 'patch-lag-by-month.json'), patchLagMonth);
  await writeJson(join(AGG_DIR, 'backlog-by-month.json'), backlogMonth);

  // Generate yearly aggregates
  console.log('Aggregating yearly data...');
  const discoveredYear = aggregateTimeSeries(records, 'year', 'discoveredDate');
  const fixedYear = aggregateTimeSeries(records, 'year', 'patchedDate');
  const patchLagYear = aggregatePatchLag(records, 'year');
  const backlogYear = aggregateBacklog(records, 'year');

  await writeJson(join(AGG_DIR, 'discovered-by-year.json'), discoveredYear);
  await writeJson(join(AGG_DIR, 'fixed-by-year.json'), fixedYear);
  await writeJson(join(AGG_DIR, 'patch-lag-by-year.json'), patchLagYear);
  await writeJson(join(AGG_DIR, 'backlog-by-year.json'), backlogYear);

  // Write manufacturer list
  await writeJson(join(AGG_DIR, 'manufacturers.json'), MANUFACTURERS as ManufacturerInfo[]);

  console.log('\n=== Aggregation complete ===');
  console.log(`Monthly: ${discoveredMonth.length} discovered, ${fixedMonth.length} fixed, ${patchLagMonth.length} patch-lag, ${backlogMonth.length} backlog`);
  console.log(`Yearly:  ${discoveredYear.length} discovered, ${fixedYear.length} fixed, ${patchLagYear.length} patch-lag, ${backlogYear.length} backlog`);
  console.log(`Manufacturers: ${MANUFACTURERS.length}`);
  console.log(`Output written to src/data/aggregated/`);
}

main().catch((err) => {
  console.error('Aggregation failed:', err);
  process.exit(1);
});
